// shopping Web App - Initial Data & State
const initialData = {
  categories: [
    { id: 'all', name_uz: 'Barchasi', name_en: 'All Items', name_ru: 'Все', icon: 'layout-grid' },
    { id: 'electronics', name_uz: 'Elektronika', name_en: 'Electronics', name_ru: 'Электроника', icon: 'laptop' },
    { id: 'smartphones', name_uz: 'Smartfonlar', name_en: 'Smartphones', name_ru: 'Смартфоны', icon: 'smartphone' },
    { id: 'clothing', name_uz: 'Kiyim-kechak', name_en: 'Clothing', name_ru: 'Одежда', icon: 'shirt' },
    { id: 'accessories', name_uz: 'Aksessuarlar', name_en: 'Accessories', name_ru: 'Аксессуары', icon: 'watch' },
    { id: 'gaming', name_uz: 'O\'yinlar & Gadjetlar', name_en: 'Gaming & Gadgets', name_ru: 'Гейминг', icon: 'gamepad-2' },
    { id: 'software', name_uz: 'Dasturiy Ta\'minot', name_en: 'Software', name_ru: 'Софт', icon: 'code' },
  ],

  products: [
    {
      id: 1,
      title_uz: 'Neon Cyberpunk Pro Eshitish Vositasi',
      title_en: 'Neon Cyberpunk Pro Headset',
      title_ru: 'Игровые наушники Neon Cyberpunk Pro',
      category: 'electronics',
      price: 849000,
      oldPrice: 1100000,
      rating: 4.9,
      reviewsCount: 128,
      image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
      tag: 'HOT',
      stock: 14,
      desc_uz: '7.1 Surround ovoz, shovqinni bosuvchi RGB mikrofon va yuqori chastotali immersiv audio.',
      desc_en: '7.1 Surround sound, noise-canceling RGB mic, and high-frequency immersive audio.',
      desc_ru: '7.1 объемный звук, RGB микрофон с шумоподавлением и мощные басы.'
    },
    {
      id: 2,
      title_uz: 'Quantum Ultra Smart Watch v4',
      title_en: 'Quantum Ultra Smart Watch v4',
      title_ru: 'Смарт-часы Quantum Ultra v4',
      category: 'accessories',
      price: 1250000,
      oldPrice: 1500000,
      rating: 4.8,
      reviewsCount: 94,
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80',
      tag: 'NEW',
      stock: 9,
      desc_uz: 'AMOLED Always-on displey, EKG, SpO2, suv o\'tkazmaydigan titanium korpus va 14 kunlik batareya.',
      desc_en: 'AMOLED Always-on display, ECG, SpO2, waterproof titanium body, and 14 days battery.',
      desc_ru: 'AMOLED дисплей, датчик ЭКГ, титановый водонепроницаемый корпус и 14 дней автономности.'
    },
    {
      id: 3,
      title_uz: 'MechGlow RGB Mexanik Klaviatura',
      title_en: 'MechGlow RGB Mechanical Keyboard',
      title_ru: 'Механическая клавиатура MechGlow RGB',
      category: 'gaming',
      price: 680000,
      oldPrice: 820000,
      rating: 4.95,
      reviewsCount: 210,
      image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80',
      tag: 'TOP',
      stock: 22,
      desc_uz: 'Hot-swappable optik switchlar, custom PBT tugmalar va 16.8 mln rangli Neon yoritish.',
      desc_en: 'Hot-swappable optical switches, custom PBT keycaps, and 16.8M RGB backlight.',
      desc_ru: 'Оптические переключатели Hot-swap, PBT кейкапы и 16.8 млн цветов подсветки.'
    },
    {
      id: 4,
      title_uz: 'CyberCore RTX 4080 Max Noutbuk',
      title_en: 'CyberCore RTX 4080 Max Laptop',
      title_ru: 'Игровой ноутбук CyberCore RTX 4080',
      category: 'electronics',
      price: 24500000,
      oldPrice: 27000000,
      rating: 5.0,
      reviewsCount: 45,
      image: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=600&q=80',
      tag: 'PREMIUM',
      stock: 5,
      desc_uz: 'Intel i9 14-avlod, 32GB DDR5 RAM, 2TB NVMe SSD, 240Hz 2K Mini-LED displey.',
      desc_en: 'Intel i9 14th Gen, 32GB DDR5 RAM, 2TB NVMe SSD, 240Hz 2K Mini-LED display.',
      desc_ru: 'Процессор Intel i9 14-поколения, 32GB ОЗУ, 2TB SSD, 240Hz Mini-LED экран.'
    },
    {
      id: 5,
      title_uz: 'NeonTech Minimalist Xudiy (Cyber Edition)',
      title_en: 'NeonTech Minimalist Hoodie (Cyber Edition)',
      title_ru: 'Худи NeonTech Minimalist Cyber Edition',
      category: 'clothing',
      price: 390000,
      oldPrice: 480000,
      rating: 4.7,
      reviewsCount: 82,
      image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80',
      tag: 'TREND',
      stock: 30,
      desc_uz: '100% paxta, lyuminestsent aks ettiruvchi logotip va zamonaviy oversize bichim.',
      desc_en: '100% premium cotton, fluorescent reflective logo, and modern oversize fit.',
      desc_ru: '100% плотный хлопок, светоотражающие неоновые принты и стиль oversize.'
    },
    {
      id: 6,
      title_uz: 'AeroSound Pro TWS Simsiz Quloqchin',
      title_en: 'AeroSound Pro TWS Wireless Earbuds',
      title_ru: 'Беспроводные наушники AeroSound Pro TWS',
      category: 'accessories',
      price: 499000,
      oldPrice: 650000,
      rating: 4.85,
      reviewsCount: 167,
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80',
      tag: 'SALE',
      stock: 18,
      desc_uz: 'Faol shovqinni bekor qilish (ANC), shaffoflik rejimi va 36 soatlik umumiy quvvat.',
      desc_en: 'Active Noise Cancellation (ANC), Transparency mode, and 36h battery life.',
      desc_ru: 'Активное шумоподавление ANC, режим прозрачности и до 36 часов работы.'
    }
  ],

  subscriptionTiers: [
    {
      id: 'standart',
      name_uz: 'Standart',
      name_en: 'Standard',
      name_ru: 'Стандарт',
      price: '0 UZS',
      period_uz: '/oyiga',
      period_en: '/month',
      period_ru: '/мес',
      isPopular: false,
      badge: 'Boshlang\'ich',
      features_uz: [
        'Cheklanmagan mahsulot ko\'rish',
        'Oddiy yetkazib berish xizmati',
        '24/7 asosiy qo\'llab-quvvatlash',
        'Standart savatcha limiti'
      ],
      features_en: [
        'Unlimited product browsing',
        'Standard delivery service',
        '24/7 basic support',
        'Standard cart limits'
      ],
      features_ru: [
        'Неограниченный просмотр товаров',
        'Стандартная доставка',
        '24/7 базовая поддержка',
        'Стандартные лимиты корзины'
      ],
      btnText_uz: 'Tanlash (Bepul)',
      btnText_en: 'Select (Free)',
      btnText_ru: 'Выбрать (Бесплатно)'
    },
    {
      id: 'pro',
      name_uz: 'Pro Foydalanuvchi',
      name_en: 'Pro Member',
      name_ru: 'Pro Подписка',
      price: '149,000 UZS',
      period_uz: '/oyiga',
      period_en: '/month',
      period_ru: '/мес',
      isPopular: true,
      badge: 'Eng Ommabop ⭐',
      features_uz: [
        'Barcha Standart imkoniyatlar',
        'Bepul Ekspress Yetkazib berish',
        'Eksklyuziv Neon chegirmalar (15%)',
        'Shaxsiy menejer va ustuvor navbat',
        'Maxsus sovg\'a vaucherlari'
      ],
      features_en: [
        'All Standard features',
        'Free Express Delivery',
        'Exclusive Neon discounts (15%)',
        'Personal manager & priority queue',
        'Special gift vouchers'
      ],
      features_ru: [
        'Все функции Стандарта',
        'Бесплатная экспресс-доставка',
        'Эксклюзивные скидки 15%',
        'Персональный менеджер и приоритет',
        'Специальные подарки и бонусы'
      ],
      btnText_uz: 'A\'zo bo\'lish (Pro)',
      btnText_en: 'Upgrade to Pro',
      btnText_ru: 'Оформить Pro'
    },
    {
      id: 'enterprise',
      name_uz: 'Enterprise / Biznes',
      name_en: 'Enterprise / Business',
      name_ru: 'Enterprise / Бизнес',
      price: '499,000 UZS',
      period_uz: '/oyiga',
      period_en: '/month',
      period_ru: '/мес',
      isPopular: false,
      badge: 'Korporativ',
      features_uz: [
        'Barcha Pro imkoniyatlar',
        'Ulgurji narxlarda xarid qilish',
        'API & B2B Dashboard integratsiyasi',
        'Kafolatlangan keshbek (5%)',
        'Maxsus xizmat ko\'rsatish SLA'
      ],
      features_en: [
        'All Pro features',
        'Wholesale pricing access',
        'API & B2B Dashboard integration',
        'Guaranteed cashback (5%)',
        'Dedicated SLA support'
      ],
      features_ru: [
        'Все преимущества Pro',
        'Доступ к оптовым ценам',
        'Интеграция API и B2B дашборда',
        'Гарантированный кешбэк 5%',
        'Персональное SLA соглашение'
      ],
      btnText_uz: 'Bog\'lanish (Biznes)',
      btnText_en: 'Contact Business',
      btnText_ru: 'Подключить Бизнес'
    }
  ],

  reviews: [
    {
      id: 1,
      author: 'Salim Aliyev',
      role: 'Dasturchi / Tech Enthusiast',
      rating: 5,
      date: '2 soat oldin',
      comment_uz: 'Juda qulay platforma! Mahsulotlar sifati a\'lo darajada, Neon dizayn esa juda zamonaviy va ko\'zni charchatmaydi.',
      comment_en: 'Awesome platform! The quality is top notch and the Neon design is sleek and modern.',
      comment_ru: 'Отличная платформа! Качество товаров на высоте, неоновый интерфейс очень стильный.',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80',
      verified: true
    },
    {
      id: 2,
      author: 'Malika Karimova',
      role: 'UI/UX Dizayner',
      rating: 5,
      date: '1 kun oldin',
      comment_uz: 'Ekspress yetkazib berish juda tez ishladi. Savatcha va to\'lov jarayoni 1 daqiqada yakunlandi. Tavsiya qilaman!',
      comment_en: 'Express delivery was super fast. Cart and checkout took just a minute. Highly recommend!',
      comment_ru: 'Быстрая доставка и очень понятный процесс оформления заказа. Рекомендую!',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
      verified: true
    },
    {
      id: 3,
      author: 'Nodirbek Usmonov',
      role: 'Tadbirkor',
      rating: 4.8,
      date: '3 kun oldin',
      comment_uz: 'Pro a\'zolik oldim, 15% chegirmalar va bepul yetkazib berish darhol o\'zini oqladi. Zo\'r xizmat.',
      comment_en: 'Subscribed to Pro, the 15% discount and free shipping are completely worth it!',
      comment_ru: 'Купил подписку Pro, скидки и бесплатная доставка сразу окупились. Супер сервис.',
      avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&q=80',
      verified: true
    }
  ],

  activityLogs: [
    {
      id: 1,
      type: 'product_add',
      icon: 'box',
      badge_uz: 'Yangi Mahsulot',
      badge_en: 'New Item',
      badge_ru: 'Новый товар',
      badgeColor: 'emerald',
      title_uz: 'Yangi tovar qo\'shildi: "CyberCore RTX 4080"',
      title_en: 'New item added: "CyberCore RTX 4080"',
      title_ru: 'Добавлен товар: "CyberCore RTX 4080"',
      time: '5 daqiqa oldin'
    },
    {
      id: 2,
      type: 'order_completed',
      icon: 'check-circle-2',
      badge_uz: 'Buyurtma Bajarildi',
      badge_en: 'Order Completed',
      badge_ru: 'Заказ выполнен',
      badgeColor: 'cyan',
      title_uz: 'Buyurtma #84920 to\'liq yetkazildi (Payme orqali)',
      title_en: 'Order #84920 delivered successfully (Payme)',
      title_ru: 'Заказ #84920 успешно доставлен (Payme)',
      time: '18 daqiqa oldin'
    },
    {
      id: 3,
      type: 'subscription',
      icon: 'sparkles',
      badge_uz: 'Pro A\'zolik',
      badge_en: 'Pro Subscription',
      badge_ru: 'Pro Подписка',
      badgeColor: 'violet',
      title_uz: 'Foydalanuvchi "Pro A\'zolik" tarifiga ulandi',
      title_en: 'User upgraded to "Pro Membership"',
      title_ru: 'Пользователь оформил подписку "Pro"',
      time: '42 daqiqa oldin'
    },
    {
      id: 4,
      type: 'admin_login',
      icon: 'shield-check',
      badge_uz: 'Admin Login',
      badge_en: 'Admin Login',
      badge_ru: 'Вход администратора',
      badgeColor: 'amber',
      title_uz: 'Admin xavfsiz tizimga muvaffaqiyatli kirdi',
      title_en: 'Admin logged in safely with 2FA',
      title_ru: 'Администратор авторизовался в системе',
      time: '1 soat oldin'
    }
  ],

  translations: {
    uz: {
      brandSub: 'Platforma Mavjud Qo\'llanma & Marketplace',
      searchPlaceholder: 'Mahsulotlarni, toifalarni qidiring...',
      allCategories: 'Barcha toifalar',
      cartTitle: 'Xarid Savatchasi',
      cartEmpty: 'Savatchangiz bo\'sh',
      checkoutBtn: 'Buyurtmani rasmiylashtirish',
      total: 'Jami summa',
      discount: 'Chegirma',
      promoPlaceholder: 'Promokod (masalan: TECH2026)',
      applyPromo: 'Qo\'llash',
      addToCart: 'Savatchaga',
      viewDetails: 'Ko\'rish',
      inStock: 'Mavjud',
      outOfStock: 'Tugagan',
      tierTitle: '1. A\'zolik Turlari (Subscription Tiers)',
      reviewTitle: '2. Fikrlar va Baholash (Reviews & Rating)',
      activityTitle: '3. Faoliyat Jurnali (Activity Log)',
      adminBtn: 'Admin Dashboard Paneli',
      leaveReview: 'Fikr qoldirish',
      ratingAvg: 'Umumiy reyting',
      basedOn: 'baholar asosida',
      newProductModal: 'Yangi Mahsulot Qo\'shish',
      manageProducts: 'Mahsulotlarni Boshqarish',
      adminPlatformTitle: 'PLATFORMA MAVJUD QO\'LLANMA',
      adminPlatformSub: 'New marketplace web app on device on Antigravity server.'
    },
    en: {
      brandSub: 'Platform Guide & Marketplace',
      searchPlaceholder: 'Search products, categories...',
      allCategories: 'All Categories',
      cartTitle: 'Shopping Cart',
      cartEmpty: 'Your cart is empty',
      checkoutBtn: 'Proceed to Checkout',
      total: 'Total',
      discount: 'Discount',
      promoPlaceholder: 'Promo code (e.g. TECH2026)',
      applyPromo: 'Apply',
      addToCart: 'Add to Cart',
      viewDetails: 'Details',
      inStock: 'In Stock',
      outOfStock: 'Out of Stock',
      tierTitle: '1. Subscription Tiers',
      reviewTitle: '2. Reviews & Rating',
      activityTitle: '3. Activity Log',
      adminBtn: 'Admin Dashboard Panel',
      leaveReview: 'Write a Review',
      ratingAvg: 'Average Rating',
      basedOn: 'based on reviews',
      newProductModal: 'Add New Product',
      manageProducts: 'Manage Products',
      adminPlatformTitle: 'PLATFORMA MAVJUD QO\'LLANMA',
      adminPlatformSub: 'New marketplace web app on device on Antigravity server.'
    },
    ru: {
      brandSub: 'Руководство платформы & Маркетплейс',
      searchPlaceholder: 'Поиск товаров, категорий...',
      allCategories: 'Все категории',
      cartTitle: 'Корзина покупок',
      cartEmpty: 'Корзина пуста',
      checkoutBtn: 'Оформить заказ',
      total: 'Итого',
      discount: 'Скидка',
      promoPlaceholder: 'Промокод (напр. TECH2026)',
      applyPromo: 'Применить',
      addToCart: 'В корзину',
      viewDetails: 'Детали',
      inStock: 'В наличии',
      outOfStock: 'Нет в наличии',
      tierTitle: '1. Виды подписок (Subscription Tiers)',
      reviewTitle: '2. Отзывы и оценки (Reviews & Rating)',
      activityTitle: '3. Журнал активности (Activity Log)',
      adminBtn: 'Панель Администратора',
      leaveReview: 'Оставить отзыв',
      ratingAvg: 'Общий рейтинг',
      basedOn: 'на основе отзывов',
      newProductModal: 'Добавить товар',
      manageProducts: 'Управление товарами',
      adminPlatformTitle: 'PLATFORMA MAVJUD QO\'LLANMA',
      adminPlatformSub: 'Новое веб-приложение маркетплейса на сервере Antigravity.'
    }
  }
};
